# Generated by Django 3.0.5 on 2020-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
